---
- name: Converge
  hosts: all
  tasks:
    - name: Include ansible-mysql
      include_role:
        name: ansible-mysql

    - name: Include ansible-powerdns-authoritative
      include_role:
        name: ansible-powerdns-authoritative
